apiVersion: sitewhere.io/v1alpha3
kind: SiteWhereInstance
metadata:
  name: sitewhere
spec:
  name: SiteWhere
  description: "Simple microservice test instance"
  configurationTemplate: default
  datasetTemplate: default
  